version: 1

defaults:
  label_selector: "AUTOBACKUP=true"
  retention_label: "AUTOBACKUP.KEEP-MAX"
  keep_max: 5
  keep_latest: 2
  keep_targets: [1d, 1w, 2w]
  snapshot_name: "%name%-%timestamp%"
  operation_timeout: 1h
  project_concurrency: 4
  server_concurrency: 4

projects:
  - name: production
    include:
      - "id:123456"
      - "name:database"
    exclude:
      - "name:temporary"
